- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install Docker
      apt: name=docker.io state=present
    - name: Start Docker Service
      systemd: name=docker state=started
    - name: Deploy Docker Container
      docker_container:
        name: healthcare1
        image: shankerchauhan/projects:healthcare1
        state: started
        ports:
          - "8084:8081"


